### ISSUE TITLE
Add support for phpstan

### ISSUE THREAD

**Issue by markdorison** [ddev/ddev-drupal-contrib#13]
## Description
[GitLab CI configures and runs phpstan against contrib modules](https://git.drupalcode.org/search?search=phpstan&nav_source=navbar&project_id=96292&group_id=2&search_code=true&repository_ref=1.0.x). Would it make sense to add that to run here as well?

**Comment by weitzman** [comment]
Yes, makes sense. PRs welcome.

**Comment by weitzman** [comment]
Lets continue in PR
