### ISSUE TITLE
ddev phpunit Producing Different Results Compared to GitLab CI

### ISSUE THREAD

**Issue by markdorison** [ddev/ddev-drupal-contrib#18]
## Description

Running `ddev phpunit` produces different results than when PHPUnit is run via GitLab CI

While attempting to [enable GitLab CI testing](https://www.drupal.org/project/remote_stream_wrapper_widget/issues/3402509) to the [`remote_stream_wrapper_widget` Drupal module](https://www.drupal.org/project/remote_stream_wrapper_widget), [PHPUnit tests finish with two errors](https://git.drupalcode.org/project/remote_stream_wrapper_widget/-/jobs/356581). I am trying to reproduce the failures locally using `ddev-drupal-contrib`, but when I run `ddev phpunit` the tests pass.

## To Reproduce

1. Run the [installation steps defined in this module's README](https://github.com/ddev/ddev-drupal-contrib?tab=readme-ov-file#install):
    1.  [Clone `remote_stream_wrapper_widget`](https://www.drupal.org/project/remote_stream_wrapper_widget/git-instructions).
    1. `ddev config --project-name=remote-stream-wrapper-widget --project-type=drupal10 --docroot=web --create-docroot --php-version=8.1`
    1. `ddev get ddev/ddev-drupal-contrib`
    1. `ddev start`
    1. `ddev poser`
    1. `ddev symlink-project`
1. Fetch [issue](https://www.drupal.org/project/remote_stream_wrapper_widget/issues/3402509) fork: 
    `git remote add remote_stream_wrapper_widget-3402509 git@git.drupal.org:issue/remote_stream_wrapper_widget-3402509.git
git fetch remote_stream_wrapper_widget-3402509`
1. Checkout issue branch: 
    `git checkout -b '3402509-enable-gitlab-ci' --track remote_stream_wrapper_widget-3402509/'3402509-enable-gitlab-ci'`
1. Run `ddev phpunit`

## Expected Behavior
I expect(? hope? 😄) to get the same results when running `ddev phpunit` using this integration as I see when GitLab CI is run with the default Drupal.org configuration.

### GitLab CI Failures
![CleanShot 2023-11-17 at 16 49 50@2x](https://github.com/ddev/ddev-drupal-contrib/assets/20355/00ed3b3c-1608-44e5-9a5d-20b26e0f393b)

### DDEV Passes
![CleanShot 2023-11-17 at 16 53 32@2x](https://github.com/ddev/ddev-drupal-contrib/assets/20355/74daf08b-6050-497a-af87-d1a7cb7db023)

**Comment by weitzman** [comment]
Now you complain about green! Just kidding. I'm curious if you ever dig in to the failures and perhaps that will shed light on whether the pass with ddev is legit.
