### ISSUE TITLE
Add `.gitignore` file, excluding `vendor`, `web`, `.ddev`, `.editorconfig`, etc. by default

### ISSUE THREAD

**Issue by gitressa** [ddev/ddev-drupal-contrib#25]
It would be nice if, when getting set up with a contrib project, if a `.gitignore` file could also be created that excludes the `vendor` and `web` folders and the `.editorconfig` and `.gitattributes` files. Maybe an optional line for excluding `.ddev/` as well. (originally suggested by @mbomb007 in #20)

For inspiration, see [Add gitignore(s) to Composer-ready project templates](https://www.drupal.org/project/drupal/issues/3082958).

**Comment by weitzman** [comment]
IMO not the job of this project. I suggest making an MR to the project which adds this file.

**Comment by gitressa** [comment]
But there is no file, or other project adding a file ... I (and @mbomb007) are suggesting that DDEV Drupal Contrib adds this file.

**Comment by weitzman** [comment]
I mean that .gitignore should be in a project's codebase. And so should .ddev IMO

**Comment by gitressa** [comment]
I think I haven't seen a contrib module with a `.ddev` folder ... In my mind, it wouldn't be much more than adding this in a `.gitignore` file in the root of the project:

```
.gitignore
.editorconfig
.gitattributes
.ddev/
/vendor/
/web/
```

Then, if you check with `git status`, none of the irrelevant Drupal core files are tracked, only changes to a contrib module file, for example `config_enforce_devel.module`:

```
user:~/dev/config_enforce_devel$ git status
On branch 1.0.x
Your branch is up to date with 'origin/1.0.x'.

nothing to commit, working tree clean
```

**Comment by claudiu-cristea** [comment]
It's OK to have .ddv committed, however, I would like to exclude it from export in `.gitattributes`. But `ddev poser` restore it every time and add it in .gitignore. How can I keep `.gitattributes` in VCS?

**Comment by rfay** [comment]
Interested in this. It does seem like people could make a mistake and commit wrong things with the untracked files. 

Recent slack conversation, https://drupal.slack.com/archives/C5TQRQZRR/p1778536315223629

**Comment by darthsteven** [comment]
It would be 'nicer' if the DDEV contrib stuff all happened in some easily ignorable subdirectory imo.
Then you'd only need to add a single directory to your contrib gitignore beyond maybe `.ddev`?

**Comment by weitzman** [comment]
See #177
