### ISSUE TITLE
How do I run `ddev poser` with no interaction?

### ISSUE THREAD

**Issue by mbomb007** [ddev/ddev-drupal-contrib#31]
How do I run `ddev poser` with no interaction? Currently, it asks me to allow plugins.

```
...
Package operations: 168 installs, 0 updates, 0 removals
  - Downloading drupal/ctools (4.0.4)
  - Downloading drupal/token (1.13.0)
  - Installing composer/installers (v2.2.0): Extracting archive
  - Installing cweagans/composer-patches (1.7.3): Extracting archive
  - Installing drupal/core-composer-scaffold (10.2.3): Extracting archive
php-http/discovery contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "php-http/discovery" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

In this [comment](https://github.com/ddev/ddev/issues/2938#issuecomment-816688010), I can see that most ddev commands allow `-y` flag. There is also `DDEV_NO_INTERACTION=TRUE` environment variable. Neither of those work for `ddev poser`. In addition, there's no "help" argument for `ddev poser` to see what flags are available. If I run `ddev poser -h` or `ddev poser --help`, it just runs as if there was no flag.

Please consider adding a `-y` flag and help flags.

**Comment by weitzman** [comment]
You can set the composer env variable for no interaction https://getcomposer.org/doc/03-cli.md#composer-no-interaction

**Comment by weitzman** [comment]
PRs welcome for better help for our commands
