### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by JimBacon** [ddev/ddev-drupal-contrib#59]
The installation instructions say

> Configure DDEV for Drupal 10 using `ddev config --project-name=[contrib module] --docroot=web  --php-version=8.1`

Much later on there is a troubleshooting section which says 

> The commands from this addon are available when the project type a valid `drupal` type. [sic]

To avoid the commands from failing, the need for the troubleshooting section, and general sadness, you could update the config command to `ddev config --project-name=[contrib module] --docroot=web  --php-version=8.1 --project-type=drupal` for the situation when the type autodetection does not work.

**Comment by simesy** [comment]
I also had some issues setting it up, it needs a fresh-eyes review against the latest ddev.

**Comment by weitzman** [comment]
As of rc17 our commands show up for any project type. See https://github.com/ddev/ddev-drupal-contrib/commit/903026a2fef564b1b7b1fb54213ebb669267995b. And yes, we aim to instruct with the assumption user has latest ddev.

**Comment by weitzman** [comment]
We now say `--project-type=drupal` in readme
