### ISSUE TITLE
Feature Request: `ddev poser` should install Drush

### ISSUE THREAD

**Issue by mbomb007** [ddev/ddev-drupal-contrib#64]
If you run `ddev poser`, and then try to run Drush, you can't because it's not installed. If you then try to install it with `ddev composer require drush/drush`, it won't work, because composer.json isn't expanded.

https://github.com/ddev/ddev-drupal-contrib/blob/main/commands/web/poser

Consider this:

```bash
export COMPOSER=composer.contrib.json
.ddev/commands/web/expand-composer-json "$DDEV_PROJECT_NAME"
composer install
composer require drush/drush
rm composer.contrib.json composer.contrib.lock
yarn --cwd $DDEV_DOCROOT/core install
touch $DDEV_DOCROOT/core/.env
```

**Comment by stasadev** [comment]
Consider this, `drush/drush` may be already there or be installed with an indirect dependency:

```bash
if ! composer show drush/drush &>/dev/null; then
    composer require drush/drush
fi
```

**Comment by weitzman** [comment]
Not gonna complicate _poser_ with that. Lets add docs like "Any development dependencies (e.g. Drush) should be added to require-dev in your project's composer.json.

**Comment by weitzman** [comment]
Doc added in https://github.com/ddev/ddev-drupal-contrib/commit/abf39994ed15370df5c7cd83e1250da8f1f03233
