### ISSUE TITLE
Drupal 11 support for `ddev phpunit`

### ISSUE THREAD

**Issue by mscieszka** [ddev/ddev-drupal-contrib#65]
I have installed Drupal 11.0-dev to investigate issues with the `phpunit (next major)` pipeline in https://gitlab.com/drupalspoons/devel/-/jobs/7146821758. Pipeline from gitlab templates invokes phpunit differently than ddev-drupal-contrib:
```
sudo -u www-data -E vendor/bin/phpunit  --bootstrap /builds/drupalspoons/devel/web/core/tests/bootstrap.php /builds/drupalspoons/devel/web/modules/custom/devel --log-junit /builds/drupalspoons/devel/junit.xml  
```

When I try to run phpunit in my local project using `ddev phpunit`, I get the following error:
![obraz](https://github.com/ddev/ddev-drupal-contrib/assets/79609951/f40b2422-59dd-4cde-bf9a-25e1f66d29ea)

[The PHPUnit 10.5 documentation](https://docs.phpunit.de/en/10.5/textui.html) seems to indicate that there is no `--printer` flag.

In .ddev/commands/phpunit there is the following code:
`phpunit --printer="\Drupal\Tests\Listeners\HtmlOutputPrinter" --bootstrap $PWD/$DDEV_DOCROOT/core/tests/bootstrap.php --testdox $DDEV_DOCROOT/modules/custom "$@"`

I have noticed that HtmlOutputPrinter is present in [Drupal 10.3](https://git.drupalcode.org/project/drupal/-/blob/10.3.x/core/tests/Drupal/Tests/Listeners/HtmlOutputPrinter.php), but has been moved/removed/modified in 11.x.

After some digging I have found [Drupal\TestTools\Extension\HtmlLogging\HtmlOutputLogger](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/tests/Drupal/TestTools/Extension/HtmlLogging/HtmlOutputLogger.php) that might be helpful.

However, simply removing `--printer="\Drupal\TestTools\Extension\HtmlLogging\HtmlOutputLogger"` part of the command so that only `phpunit --bootstrap $PWD/$DDEV_DOCROOT/core/tests/bootstrap.php --testdox $DDEV_DOCROOT/modules/custom "$@"` remains, allows phpunit to run properly (still, I am not sure if output is formatted/handled as expected):
![obraz](https://github.com/ddev/ddev-drupal-contrib/assets/79609951/bb2815b6-16e9-4419-84b2-a9aa869aa2be)

**Comment by weitzman** [comment]
FYI We removed --testdox recently in https://github.com/ddev/ddev-drupal-contrib/pull/63. 

We do want to keep the browser output so lets see how to fix this properly.

**Comment by weitzman** [comment]
I removed --printer in #70. I think the debug files are saved just by the fact that we set BROWSERTEST_OUTPUT_DIRECTORY. We can add back the links if we want. See https://www.drupal.org/project/drupal/issues/3452519
