### ISSUE TITLE
ddev symlink-project does not run automatically on ddev start as README states

### ISSUE THREAD

**Issue by markdorison** [ddev/ddev-drupal-contrib#66]
From the README:

> [ddev symlink-project](https://github.com/ddev/ddev-drupal-contrib/blob/main/commands/web/symlink-project). This symlinks the top level files of your project into web/modules/custom so that Drupal finds your module. **_This command runs automatically on every ddev start._** See codebase image below.

In my testing, I have seen this not occur and I then need to run `ddev symlink-project` manually. Could this be a bug or maybe the documentation is out of date?

**Comment by rfay** [comment]
Here's how it happens, and it only happens  if`vendor/autoload.php` is there already:

https://github.com/ddev/ddev-drupal-contrib/blob/abf39994ed15370df5c7cd83e1250da8f1f03233/config.contrib.yaml#L10-L17

IMO the `else` there is incorrect, and of course the symlink is *not* done on every start I don't think

**Comment by markdorison** [comment]
That clarifies things. Thanks @rfay! I created PR #67 to update the README to include this scenario.
