### ISSUE TITLE
Yarn failure with Drupal 11

### ISSUE THREAD

**Issue by weitzman** [ddev/ddev-drupal-contrib#69]
With Drupal 11, I am seeing yarn fail at the end of `ddev poser` with a suggestion to use corepack. Help wanted on adapting to this. I know DDEV did some work to make this easier but work is needed here too, it seems. The error I see happens with latest released DDEV

**Comment by rfay** [comment]
DDEV automatically detects D11 and enables `corepack_enable` in that case. 

`ddev config --update` will automatically detect and change.

**Comment by weitzman** [comment]
For now I have removed the yarn call from `ddev poser` so this issue is moot. I'll close it in a few days.
