### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by tbutterf** [ddev/ddev-drupal-contrib#72]
I have been unable to get `ddev poser` to read in my patches. I may be doing it wrong. But, I'm adding the following to the composer.json file in the `extras` section:
```
"enable-patching": true,
"patches": {
    "drupal/fontawesome": {
        "#3274028: Fixing CKEditor 5 compatibility": "https://www.drupal.org/files/issues/2024-01-17/ckeditor_compatibility_issue_0.patch",
        "#3274028: Fixing CKEditor 5 inline Icons": "https://www.drupal.org/files/issues/2024-01-16/fix_inline_icons_0.patch",
        "3417901: Breaking change introduced in a38b572": "https://www.drupal.org/files/issues/2024-01-29/fontawesome-prefixbug-3417901-1.patch"
    }
}
```

**Comment by weitzman** [comment]
Does your project depend on the cweagans package? Thats required. Please link to the project's composer.json so we can see.

The file that does the heavy lifting is https://git.drupalcode.org/project/gitlab_templates/-/raw/default-ref/scripts/expand_composer_json.php. Thats maintained by the gitlab_templates project from the Drupal Assoc.

**Comment by tbutterf** [comment]
Interesting. I was going off the assumption that I didn't need to include the cweagans package in my project because of this line in the ddev-drupal-contrib README.md: `cweagans/composer-patches:^1 is added by ddev poser so feel free to configure any patches that your project needs.` I wonder if it might be helpful to add more information to the README so that it is more clear.

I'm trying to create a Merge Request for an issue on the Fontawesome module. In order to have all the code pieces, I need to have the patches get applied. I tried adding the following to the project's composer.json file
```
"require-dev": {
        "cweagans/composer-patches": "~1.0"
    },
```
But, that didn't seem to help. Here is the full, altered, composer.json file:
```
{
    "name": "drupal/fontawesome",
    "description": "The web's most popular icon set and toolkit.",
    "type": "drupal-module",
    "license": "GPL-2.0-or-later",
    "homepage": "https://www.drupal.org/project/fontawesome",
    "minimum-stability": "dev",
    "support": {
        "issues": "https://drupal.org/project/issues/fontawesome",
        "source": "https://git.drupalcode.org/project/fontawesome"
    },
    "require": {
        "drupal/core": "^9.4 || ^10"
    },
    "require-dev": {
        "cweagans/composer-patches": "~1.0"
    },
    "extra": {
        "drush": {
            "services": {
                "drush.services.yml": "^9 || ^10 || ^11"
            }
        },
        "enable-patching": true,
        "patches": {
            "drupal/fontawesome": {
                "#3274028: Fixing CKEditor 5 compatibility": "https://www.drupal.org/files/issues/2024-01-17/ckeditor_compatibility_issue_0.patch",
                "#3274028: Fixing CKEditor 5 inline Icons": "https://www.drupal.org/files/issues/2024-01-16/fix_inline_icons_0.patch",
                "3417901: Breaking change introduced in a38b572": "https://www.drupal.org/files/issues/2024-01-29/fontawesome-prefixbug-3417901-1.patch"
            }
        }
    }
}
```

**Comment by weitzman** [comment]
You are right. You dont need to add cweagans as a dependency. I got it working on Devel just now with this snippet in composer.json

```
"extra": {
        "patches": {
            "drupal/core": {
                "Add startup configuration for PHP server": "https://git.drupalcode.org/project/drupal/-/merge_requests/6790.patch"
            }
        }
    }
```
