### ISSUE TITLE
Use custom module name in symlink-project, different from DDEV_SITENAME

### ISSUE THREAD

**Issue by donquixote** [ddev/ddev-drupal-contrib#74]
I have this situation where the ddev project/site name is different from the desired module name.

Currently the project name is like "something-drupal" whereas the module name should be like "something_banana".
So the symlinks should go to `web/modules/custom/something_banana` and not `web/modules/custom/something_drupal`.
What makes this relevant is that the project contains hard-coded paths which assume a directory name.
(Let's not go into detail about how the problems with my setup are a bit silly. It's an existing project.)

A less silly case could be if we want to have 2 instances in 2 separate dirs for the same project.
So one would be `something` the other would be `something-1`.
Currently, symlink-project would create `web/modules/custom/something` in one project dir, and `web/modules/custom/something_1` in the other project dir.

Would it make sense to decouple the module dir name from the `DDEV_SITENAME` env variable?

**Comment by weitzman** [comment]
I'm not too interested in supporting "interesting" and edge case setups. Feel free to push a PR up and folks can use the patch when needed.
