### ISSUE TITLE
ddev poser require foo/bar

### ISSUE THREAD

**Issue by geek-merlin** [ddev/ddev-drupal-contrib#91]
For working on my modules, i finnally swapped spoons for this. Great work, very helpful!

Now i'm working on a module (page_manager), and need drush, but it's not installed by `ddev poser`.
I don't want to require-dev it in the module (but did it as a workaround).
For drupalspoons i could require in composer.spoons.json, and castor also allows it, so i tried `ddev poser require drush/drush`, but it seems not to be implemented.

Sth like this would be very helpful!

**Comment by weitzman** [comment]
Why dont you want it in require-dev?

**Comment by geek-merlin** [comment]
There are quite some modules i work on, for which i'm not maintainer and don't want to argue more issues about what should be in require-dev.

Also i have some dev helper packages that are not suitable for other people's composer.json because they are quite opinionated, so i need a kind of require-dev-local.
