### ISSUE TITLE
Use into a DDEV Project. Is it possible?

### ISSUE THREAD

**Issue by juagarc4** [ddev/ddev-drupal-contrib#96]
I find this module really useful to add testing capabilities and I want to use it for my project.
However I followed the instructions and I realized that it won't work in my project because I'm already using DDEV in the project I'm working on.

Also, the 4th step `ddev configure.... ` shows the ddev error:
`"it usually does not make sense to `ddev config` in a subdirectory of an existing project. Is it possible you wanted to `ddev config` in parent directory ...?"`

As far I understand this project is not intended to be used into a DDEV project or am I wrong and is there then any way to use this project into a DDEV project? 

Thanks in advance
Regards

**Comment by weitzman** [comment]
You have to start with a clone of the contrib project. That must be in the root of the project for this add-on to work.

**Comment by juagarc4** [comment]
Aha, 
I understand it. 

As I supposed I can't just add this tool to my current project but I have to start a new one without DDEV an then use this tool in that project.

Thanks for the explanation.
